cards = [
('DelayedChill', '迟来的寒意', '造成{Damage}点伤害。\n给予5层寒霜。若为解冻牌，改为10层。', '1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 8, DamageUpgrade: 3'),
('PiercingCold', '透骨寒芒', '造成{Damage}点伤害。\n给予等于未被格挡伤害一半的寒霜（向下取整）。', '2, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 18, DamageUpgrade: 6'),
('SnowFinale', '雪蚀终章', '造成{Damage}点伤害。\n本场战斗每因自霜实际失去1点生命，此次伤害增加2。', '2, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy, Damage: 10, DamageUpgrade: 4'),
('SpreadFrost', '蔓延', '给予所有敌人{Amount}层寒霜。\n每有一名正被冰封的敌人，获得3层雪势。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.AllEnemies, Amount: 5, AmountUpgrade: 2'),
('FrostCarving', '霜中雕刻', '冷藏1张牌。\n下次解冻该牌时，获得{Amount}张冰晶。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
('FrozenMoment', '冰封时刻', '可以冷藏最多3张牌。\n下回合多抽2张牌。\n消耗。', '2, CardType.Skill, CardRarity.Rare, TargetType.Self, Exhaust: true, CostUpgrade: -1'),
('PhaseShift', '相变', '选择一项：\n将至多{Amount}层冰甲转为目标的寒霜。\n或碎冰{Amount}，获得等量冰甲。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.AnyEnemy, Amount: 10, AmountUpgrade: 5'),
('ColdSearch', '冰库检索', '获得{Block}点格挡。\n从抽牌堆选择1张攻击牌冷藏。\n消耗。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Block: 4, BlockUpgrade: 3, Exhaust: true'),
('BloodWinter', '以血封冬', '失去4点生命。\n抽{Amount}张牌。\n可以冷藏最多2张牌。\n消耗。', '1, CardType.Skill, CardRarity.Rare, TargetType.Self, Amount: 3, AmountUpgrade: 1, Exhaust: true'),
('DebtSettlement', '霜债清算', '消耗至多{Amount}层冰甲，每4层移除1层自霜。\n每移除1层自霜，抽1张牌。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 8, AmountUpgrade: 4'),
('QuietMeditation', '静雪冥想', '下回合抽牌前，获得2点能量与{Amount}层雪势。\n消耗。', '1, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 1, AmountUpgrade: 1, Exhaust: true'),
('ShardBurst', '冰屑迸发', '每回合每失去8层冰甲，获得1张冰晶。\n每回合最多{Amount}次。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
('CrystalResonance', '晶群共鸣', '每次生成冰晶时，额外生成{Amount}张。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
('WinterArchive', '漫冬档案', '回合结束、弃牌之前，可以冷藏最多{Amount}张手牌。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
('EndlessStorm', '永夜风暴', '雪势在回合结束时只减少{Amount}层。', '3, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 2, AmountUpgrade: -1'),
('SixfoldSnow', '雪花六出', '每当你打出解冻牌，获得{Amount}张冰晶。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
('PolarCycle', '极夜循环', '回合结束时，若本回合：\n碎冰过，获得{Armor}层冰甲。\n冷藏过，获得{Amount}层雪势。\n消耗过冰晶，下回合多抽1张牌。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
('HiddenBlade', '藏锋秘术', '解冻后的下一次打出，攻击牌每段伤害增加{Amount}。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 4, AmountUpgrade: 2'),
('ColdBloodEcho', '寒血回响', '自霜使你失去生命时，获得损失{Amount}倍的冰甲。每回合限1次。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
('HeatExchange', '热交换', '每回合首次解冻基础费用至少2的牌时，获得1点能量。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 1, CostUpgrade: -1'),
]
powers = {
 'ShardBurstPower':('冰屑迸发', '每回合每失去8层冰甲，获得{Amount}张冰晶。每回合最多{Limit}次。'),
 'CrystalResonancePower':('晶群共鸣', '每次生成冰晶时，额外生成{Amount}张。'),
 'WinterArchivePower':('漫冬档案','回合结束、弃牌前，可以冷藏最多{Amount}张手牌。'),
 'EndlessStormPower':('永夜风暴', '雪势在回合结束时只减少{Decay}层。'),
 'SixfoldSnowPower':('雪花六出', '每当你打出解冻牌，获得{Amount}张冰晶。'),
 'PolarCyclePower':('极夜循环', '回合结束：碎冰过，获得{Armor}层冰甲；冷藏过，获得{Amount}层雪势；消耗过冰晶，下回合多抽{Draw}张牌。'),
 'HiddenBladePower':('藏锋秘术', '解冻后的下一次打出，攻击牌每段伤害增加{Amount}。'),
 'ColdBloodEchoPower':('寒血回响', '自霜使你失去生命时，获得损失{Amount}倍的冰甲。每回合限1次。'),
 'HeatExchangePower':('热交换', '每回合首次解冻基础费用至少2的牌时，获得{Amount}点能量。'),
 'DrawNextPower':('冬日筹备', '下回合多抽{Amount}张牌。'),
 'MeditationPower':('静雪冥想', '下回合获得{Amount}点能量和{Snow}层雪势。'),
}
