cards = [
('GlacialCore', '极寒晶核', '冰晶额外施加{Amount}层寒霜。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
('PrismBlast', '棱光熔铸', '造成{Damage}点伤害。\n可以消耗1张手牌。若成功，获得2张冰晶。', '2, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 18, DamageUpgrade: 6'),
('IceChisel', '冰凿', '造成{Damage}点伤害。\n若目标正被冰封，此次伤害增加4。', '0, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 4, DamageUpgrade: 2'),
('ShatterVolley', '碎霜连射', '碎冰6。\n造成{Damage}点伤害3次，每移除2层寒霜，额外攻击1次。', '1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 3, DamageUpgrade: 1'),
('Frostfire', '霜火反冲', '造成{Damage}点伤害。\n获得2层自霜。', '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 14, DamageUpgrade: 4'),
('Ricochet', '折光弹射', '随机对敌人造成{Damage}点伤害3次。\n冷藏区中若有牌，获得1张冰晶。', '1, CardType.Attack, CardRarity.Common, TargetType.AllEnemies, Damage: 3, DamageUpgrade: 1'),
('CrystalVolley', '万棱齐射', '消耗所有手牌中的冰晶。\n造成{Damage}点伤害。每消耗1张，额外攻击1次。', '2, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy, Damage: 8, DamageUpgrade: 4'),
('SnowBurial', '雪葬', '造成{Damage}点伤害，冷藏区每有1张牌，此次伤害增加3。\n冷藏区若有至少3张牌，给予2层虚弱。', '3, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy, Damage: 24, DamageUpgrade: 8'),
('WhiteBreath', '白龙吐息', '对所有敌人造成{Damage}点伤害。\n失去所有冰甲和雪势，每失去3层，给予所有敌人1层寒霜。', '3, CardType.Attack, CardRarity.Rare, TargetType.AllEnemies, Damage: 18, DamageUpgrade: 6'),
('Grind', '研磨', '可以消耗最多2张牌。\n每消耗1张，抽{Amount}张牌。\n消耗。', '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1, Exhaust: true'),
('IceDust', '冰尘', '消耗1张牌。\n获得{Amount}层冰甲和2层雪势。', '1, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 4, AmountUpgrade: 2'),
('SeekWinter', '寻冬', '抽{Amount}张牌，然后丢弃1张牌。', '1, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 3, AmountUpgrade: 1'),
('PermafrostWard', '冻土结界', '获得{Amount}层冰甲。\n可以冷藏1张牌。\n移除最多2层自霜。', '2, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 12, AmountUpgrade: 4'),
('WarmthRecovery', '余热回收', '消耗手牌中的1张冰晶。\n若消耗，抽{Amount}张牌。\n消耗。', '0, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 2, AmountUpgrade: 1, Exhaust: true'),
('ThawEnergy', '解冻供能', '解冻1张牌。若成功，获得{Amount}点能量。\n获得2层自霜。\n消耗。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1, Exhaust: true'),
('CrystalFurnace', '冰燃炉', '可以消耗手牌中最多{Amount}张冰晶。\n每消耗1张，获得1点能量与1层自霜。\n消耗。', '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1, Exhaust: true'),
('CrystalEdge', '晶锋', '冰晶额外造成{Amount}点伤害，且无视格挡。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 3, AmountUpgrade: 2'),
('CrystalAmulet', '冰晶护符', '每当你消耗1张冰晶，获得{Amount}层冰甲。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
('IceCellar', '冰窖', '每当你解冻1张牌，抽{Amount}张牌。', '2, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 1, CostUpgrade: -1'),
('WinterEdict', '寒冬敕令', '每当你冰封敌人，获得{Amount}层冰甲并抽1张牌。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 6, AmountUpgrade: 3'),
('WinterStay', '留冬', '回合结束时，冷藏区若有至少2张牌，获得{Amount}层雪势。\n在雪势伤害前结算。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
]
powers = {
 'GlacialCorePower': ('极寒晶核', '冰晶额外施加{Amount}层寒霜。'),
 'CrystalEdgePower':('晶锋', '冰晶额外造成{Amount}点伤害，且无视格挡。'),
 'CrystalAmuletPower':('冰晶护符', '每当你消耗冰晶，获得{Amount}层冰甲。'),
 'IceCellarPower':('冰窖', '每当你解冻1张牌，抽{Amount}张牌。'),
 'WinterEdictPower':('寒冬敕令', '每当你冰封敌人，获得{Amount}层冰甲并抽1张牌。'),
 'WinterStayPower':('留冬', '回合结束时，若冷藏区有至少2张牌，获得{Amount}层雪势。'),
}
