# Editable card data: class, Chinese title, description, CardSpec.
cards = [('FrostStrike', '打击', '造成{Damage:diff()}点伤害。', '1, CardType.Attack, CardRarity.Basic, TargetType.AnyEnemy, Damage: 6, DamageUpgrade: 3'),
 ('FrostDefend', '防御', '获得{Block:diff()}点格挡。', '1, CardType.Skill, CardRarity.Basic, TargetType.Self, Block: 5, BlockUpgrade: 3'),
 ('CrystalRite', '深埋', '获得{Block}点格挡，从抽牌堆选择至多1张牌冷藏。', '1, CardType.Skill, CardRarity.Basic, TargetType.Self, Block: 5, BlockUpgrade: 3'),
 ('IceCrystal',
  '冰晶',
  '造成{Damage}点伤害，给予{Amount}层寒霜。\n消耗。',
  '0, CardType.Attack, CardRarity.Token, TargetType.AnyEnemy, Damage: 2, DamageUpgrade: 1, Amount: 1, AmountUpgrade: 1, Exhaust: true'),
 ('FrostShatter',
  '霜裂',
  '如果敌人至少有3层寒霜，碎冰3，获得{Amount}点力量，造成{Damage}点伤害。',
  '2, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 10, Amount: 1, AmountUpgrade: 1'),
 ('FreezeRay',
  '冻结射线',
  '造成{Damage}点伤害，给予{Amount}层寒霜。',
  '1, CardType.Attack, CardRarity.Basic, TargetType.AnyEnemy, Damage: 3, DamageUpgrade: 1, Amount: 10, AmountUpgrade: 1'),
 ('RimeCoat',
  '覆霜',
  '获得{Block}点格挡。获得{Amount}层冰甲。',
  '1, CardType.Skill, CardRarity.Common, TargetType.Self, Block: 3, BlockUpgrade: 1, Amount: 4, AmountUpgrade: 2'),
 ('Crystallize',
  '棱镜裂斩',
  '造成{Damage}点伤害2次，若本牌为解冻牌，给予{Amount}层易伤并获得1层自霜。',
  '3, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 8, DamageUpgrade: 2, Amount: 2, AmountUpgrade: 1'),
 ('CrystalCluster', '冰晶簇', '获得{Amount}张冰晶。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 3, AmountUpgrade: 1'),
 ('SnowCache', '雪藏', '冷藏1张牌，获得等于所冷藏牌基础费用{Amount}倍的雪势。', '0, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 3, AmountUpgrade: 1'),
 ('MeltSeal', '融封', '获得{Block}点格挡，解冻1张牌。', '0, CardType.Skill, CardRarity.Common, TargetType.Self, Block: 3, BlockUpgrade: 2'),
 ('WakeIce', '破冰唤醒', '随机解冻2张牌，获得2层自霜。\n消耗。', '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Exhaust: true'),
 ('OverdrawWarmth', '温度循环', '获得{Amount}点能量，获得3层自霜。', '0, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
 ('RapidCalculation', '急速演算', '抽{Amount}张牌，获得1层自霜。', '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
 ('Rewarm',
  '回温',
  '获得{Block}点格挡，失去{Amount}层自霜。',
  '1, CardType.Skill, CardRarity.Common, TargetType.Self, Block: 9, BlockUpgrade: 2, Amount: 2, AmountUpgrade: 1'),
 ('ExpandColdStore', '冷库扩张', '冷藏容量+{Amount}。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
 ('SlowRelease', '速释装置', '回合开始时，额外解冻{Amount}张牌。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
 ('ShieldCounter', '冰盾反击', '造成{Damage}点伤害，额外造成等量与你当前冰甲层数的伤害。', '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, CostUpgrade: -1, Damage: 5'),
 ('IceHarvest',
  '采冰',
  '造成{Damage}点伤害，生成{Amount}张冰晶。',
  '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 7, Amount: 1, AmountUpgrade: 1'),
 ('SnowRoll',
  '卷雪',
  '对所有敌人造成{Damage}点伤害，获得{Amount}层雪势。',
  '1, CardType.Attack, CardRarity.Common, TargetType.AllEnemies, Damage: 5, DamageUpgrade: 1, Amount: 4, AmountUpgrade: 2'),
 ('Avalanche',
  '雪崩',
  '造成{Damage}点伤害，给予{Amount}层寒霜，获得5层自霜。\n消耗。',
  '3, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy, Damage: 30, DamageUpgrade: 10, Amount: 20, AmountUpgrade: 5, Exhaust: true'),
 ('SnowSweep',
  '扫雪',
  '对所有敌人造成{Damage}点伤害，碎冰3，额外造成碎冰次数{Amount}倍的伤害。',
  '1, CardType.Attack, CardRarity.Common, TargetType.AllEnemies, Damage: 7, Amount: 2, AmountUpgrade: 1'),
 ('TwinBlades',
  '冰刃连斩',
  '造成{Damage}点伤害2次，碎冰1，额外造成{Amount}次伤害。',
  '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 4, Amount: 1, AmountUpgrade: 1'),
 ('ColdHammer',
  '冰库重锤',
  '造成{Damage}点伤害，冷藏牌的基础费用合计每有1点，额外造成{Amount}点伤害。',
  '2, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 15, Amount: 4, AmountUpgrade: 1'),
 ('MeltSlash',
  '融冰斩',
  '造成{Damage}点伤害，解冻最多{Amount}张牌。',
  '1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 8, DamageUpgrade: 1, Amount: 1, AmountUpgrade: 1'),
 ('WhiteMist',
  '冰雾刃',
  '造成{Damage}点伤害，给予4层寒霜和{Amount}层虚弱。',
  '1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 9, DamageUpgrade: 2, Amount: 1, AmountUpgrade: 1'),
 ('IceBind', '冰缚', '给予{Amount:diff()}层寒霜。\n可以冷藏1张牌。', '2, CardType.Skill, CardRarity.Uncommon, TargetType.AnyEnemy, Amount: 18, AmountUpgrade: 6'),
 ('AbsoluteZero',
  '绝对零度',
  '给予所有敌人{Amount}层寒霜。\n消耗。',
  '3, CardType.Skill, CardRarity.Rare, TargetType.AllEnemies, CostUpgrade: -1, Amount: 35, Exhaust: true'),
 ('ShellRecycle',
  '冰壳',
  '保留。\n消耗所有冰甲，获得等于所消耗冰甲2倍的格挡。\n消耗。',
  '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Retain: true, Exhaust: true, RemoveExhaustUpgrade: true'),
 ('SealSpell', '封存咒', '抽{Amount}张牌，冷藏1张牌。', '1, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 3, AmountUpgrade: 1'),
 ('BlizzardComing',
  '暴雪将至',
  '获得{Amount}层雪势，阻止你下{Extra}次获得自霜。',
  '2, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 10, AmountUpgrade: 2, Extra: 1, ExtraUpgrade: 1'),
 ('Snowline',
  '雪线推进',
  '获得2层自霜，对所有敌人造成{Damage}点伤害并获得总伤害一半的雪势。',
  '2, CardType.Attack, CardRarity.Uncommon, TargetType.AllEnemies, Damage: 7, DamageUpgrade: 3'),
 ('ThawFrost',
  '融霜',
  '获得{Amount}点冰甲，碎冰{Extra}，额外获得所碎冰层数2倍的冰甲。',
  '1, CardType.Skill, CardRarity.Common, TargetType.AnyEnemy, Amount: 5, AmountUpgrade: 1, Extra: 2, ExtraUpgrade: 1'),
 ('ColdReturn',
  '寒潮回流',
  '保留。\n获得{Amount}层雪势，获得你当前雪势层数{Extra}倍的冰甲。\n消耗。',
  '2, CardType.Skill, CardRarity.Rare, TargetType.Self, Amount: 4, AmountUpgrade: 1, Extra: 2, ExtraUpgrade: 1, Retain: true, Exhaust: true'),
 ('StepSnow',
  '踏雪追击',
  '造成{Damage}点伤害，你的冷藏区每有1张牌，抽1张牌，最多{Amount}。',
  '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 7, DamageUpgrade: 1, Amount: 2, AmountUpgrade: 1'),
 ('ThinIce', '薄冰突刺', '造成{Damage}点伤害，若目标已有寒霜，获得等量与伤害的冰甲。', '0, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 5, DamageUpgrade: 2'),
 ('SpringFlood', '春汛', '打出你冷藏牌堆里的所有牌。\n消耗。', '2, CardType.Skill, CardRarity.Rare, TargetType.Self, CostUpgrade: -1, Exhaust: true'),
 ('DeepCache',
  '藏刃',
  '造成{Damage}点伤害，冷藏至多1张牌，如果冷藏了牌，抽{Amount}张牌。',
  '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 4, Amount: 2, CostUpgrade: -1'),
 ('GlacierBody', '冰川形态', '获得{Amount}层冰甲。每回合获得1层冰甲。你的冰甲不再自然融化。', '3, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 7, AmountUpgrade: 3'),
 ('StormCore', '风暴核心', '每回合获得{Amount}层雪势。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 3, AmountUpgrade: 1'),
 ('SnowEye', '雪眼', '每当你打出冰晶，获得{Amount:diff()}层雪势。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
 ('IceMirror', '冰镜圣所', '每当你解冻1张牌，获得{Amount:diff()}层冰甲。', '1, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 3, AmountUpgrade: 1'),
 ('GlacialCore', '极寒晶核', '冰晶额外施加{Amount:diff()}层寒霜。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
 ('PrismBlast',
  '棱光熔铸',
  '造成{Damage}点伤害，选择最多{Amount}张手牌消耗，每消耗1张，获得{Extra}层雪势。',
  '3, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 16, DamageUpgrade: 2, Amount: 3, AmountUpgrade: 1, Extra: 3, ExtraUpgrade: 1'),
 ('IceChisel',
  '冰凿',
  '造成{Damage}点伤害，如果敌人至少有2层寒霜，给予{Amount}层易伤。',
  '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 7, DamageUpgrade: 1, Amount: 1, AmountUpgrade: 1'),
 ('Frostfire', '霜火反冲', '造成{Damage}点伤害，获得1层自霜。', '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 10, DamageUpgrade: 3'),
 ('CrystalVolley', '万棱齐射', '造成{Damage}点伤害，用冰晶填满你的手牌。', '2, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy, Damage: 19'),
 ('IceDust',
  '冰尘',
  '获得{Amount}层冰甲和{Extra}层雪势，消耗1张牌。',
  '1, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 6, AmountUpgrade: 1, Extra: 2, ExtraUpgrade: 1'),
 ('PermafrostWard', '冻土结界', '获得{Amount}层冰甲，可以冷藏1张牌。', '2, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 12, AmountUpgrade: 4'),
 ('WarmthRecovery',
  '余热回收',
  '选择至多{Amount}张手牌消耗，并生成等量的冰晶。\n消耗。',
  '0, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 2, AmountUpgrade: 1, Exhaust: true'),
 ('ThawEnergy',
  '“冻”能',
  '解冻至多{Amount}张牌，并获得等于解冻牌数的能量。获得1层自霜。\n消耗。',
  '1, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1, Exhaust: true'),
 ('CrystalFurnace',
  '冰晶回收',
  '消耗手牌中至多2张冰晶，每消耗一张，获得1点能量与1点自霜。\n消耗。',
  '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Exhaust: true, RetainUpgrade: true'),
 ('CrystalEdge', '晶锋', '冰晶额外造成{Amount:diff()}点伤害，且无视格挡。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 3, AmountUpgrade: 2'),
 ('CrystalAmulet', '冰晶护符', '每当你消耗1张冰晶，获得{Amount:diff()}层冰甲。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
 ('IceCellar', '冰窖', '每当你解冻1张牌，抽{Amount}张牌。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
 ('DelayedChill',
  '迟来的寒意',
  '造成{Damage}点伤害，给予{Amount}层寒霜，若本牌为解冻牌，改为{Extra}层。',
  '1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 9, DamageUpgrade: 2, Amount: 8, AmountUpgrade: 2, Extra: 12, ExtraUpgrade: 4'),
 ('PiercingCold',
  '透骨寒芒',
  '造成{Damage}点伤害，冷藏至多{Amount}张牌，每冷藏1张，额外造成1次伤害。',
  '2, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 6, Amount: 2, AmountUpgrade: 1'),
 ('SnowFinale',
  '雪蚀终章',
  '造成{Damage}点伤害，本场战斗每因自霜失去1点生命，回复1点生命。\n消耗。',
  '1, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy, Damage: 10, Exhaust: true, RemoveExhaustUpgrade: true'),
 ('SpreadFrost', '蔓延', '给予所有敌人5层寒霜，敌人每有5层寒霜，获得{Amount}层雪势。', '1, CardType.Skill, CardRarity.Uncommon, TargetType.AllEnemies, Amount: 3, AmountUpgrade: 1'),
 ('FrostCarving', '霜刻', '冷藏1张牌，下次解冻该牌时，获得{Amount}张冰晶。下回合额外解冻1张牌。', '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
 ('FrozenMoment',
  '冰封时刻',
  '可以冷藏最多{Amount}张手牌、{Amount}张弃牌堆的牌和{Amount}张抽牌堆的牌。\n消耗。',
  '1, CardType.Skill, CardRarity.Rare, TargetType.Self, Amount: 2, AmountUpgrade: 1, Exhaust: true'),
 ('PhaseShift',
  '相变',
  '碎冰10，获得等于所碎冰层数{Amount}倍的冰甲。\n消耗。',
  '2, CardType.Skill, CardRarity.Uncommon, TargetType.AnyEnemy, Amount: 2, AmountUpgrade: 1, Exhaust: true'),
 ('ColdSearch',
  '检索急冻',
  '获得{Block}点格挡，从抽牌堆选择至多{Amount}张攻击牌冷藏。\n消耗。',
  '1, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Block: 7, Amount: 1, AmountUpgrade: 1, Exhaust: true'),
 ('BloodWinter',
  '以血封冬',
  '获得3层自霜。获得1点能量，抽{Amount}张牌。冷藏手牌中的最多{Extra}张牌。\n消耗。',
  '0, CardType.Skill, CardRarity.Rare, TargetType.Self, Amount: 3, AmountUpgrade: 1, Extra: 2, ExtraUpgrade: 1, Exhaust: true'),
 ('DebtSettlement',
  '霜债清算',
  '保留。\n移除所有自霜，每移除一层自霜，抽一张牌。\n消耗。',
  '2, CardType.Skill, CardRarity.Rare, TargetType.Self, Retain: true, Exhaust: true, CostUpgrade: -1'),
 ('QuietMeditation',
  '静雪冥想',
  '在下回合获得{Amount}点能量并获得{Extra}点冰甲。',
  '1, CardType.Skill, CardRarity.Common, TargetType.Self, Amount: 2, AmountUpgrade: 1, Extra: 4, ExtraUpgrade: 2'),
 ('CrystalResonance', '晶群共鸣', '每次生成冰晶时，额外生成{Amount:diff()}张。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
 ('WinterArchive', '漫冬', '回合结束时，冷藏至多1张手牌。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 1, CostUpgrade: -1'),
 ('EndlessStorm', '永夜风暴', '雪势在回合结束时只减少{Amount:diff()}层。', '3, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 2, AmountUpgrade: -1'),
 ('SixfoldSnow', '积雪', '每回合第一次解冻牌时，获得{Amount}层冰甲。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 4, AmountUpgrade: 2'),
 ('HiddenBlade', '藏锋秘术', '攻击牌解冻后的下一次打出增加{Amount}点伤害。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 4, AmountUpgrade: 2'),
 ('ColdBloodEcho', '寒血回响', '自霜使你失去生命时，获得损失生命{Amount}倍的冰甲。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, Amount: 2, AmountUpgrade: 1'),
 ('HeatExchange', '热交换', '每回合首次解冻牌时，获得{Amount}点能量。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, Amount: 1, AmountUpgrade: 1'),
 ('SnowBloom', '霜华漫天', '最多选择你消耗牌堆里的3张牌放入冷藏牌堆。\n消耗。', '2, CardType.Skill, CardRarity.Rare, TargetType.Self, Exhaust: true, RemoveExhaustUpgrade: true'),
 ('Dissolve', '消融', '选择任意张冷藏牌堆里的牌解冻。\n消耗。', '0, CardType.Skill, CardRarity.Rare, TargetType.Self, Exhaust: true, RetainUpgrade: true'),
 ('SilverFrost',
  '银色风霜',
  '固有。\n获得{Amount}层雪势。\n消耗。',
  '1, CardType.Skill, CardRarity.Rare, TargetType.Self, Amount: 13, AmountUpgrade: 4, Innate: true, Exhaust: true'),
 ('FrozenWish',
  '冻结心愿',
  '固有。\n选择抽牌堆里的{Amount}张牌冷藏，下回合额外解冻{Amount}张牌。\n消耗。',
  '1, CardType.Skill, CardRarity.Rare, TargetType.Self, Amount: 2, AmountUpgrade: 1, Innate: true, Exhaust: true'),
 ('Glitter', '晶莹', '生成2张锐利冰晶。', '1, CardType.Skill, CardRarity.Rare, TargetType.Self'),
 ('BlessingWind', '祝福之风', '敏捷现在可以在你获得冰甲时应用。获得1层敏捷。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, InnateUpgrade: true'),
 ('HeartInscription', '铭刻于心', '力量现在可以在你获得雪势时应用。获得1层力量。', '1, CardType.Power, CardRarity.Uncommon, TargetType.Self, InnateUpgrade: true'),
 ('FlowingPower', '流淌而出的强大力量', '每当你生成一张冰晶，将其升级。', '2, CardType.Power, CardRarity.Rare, TargetType.Self, CostUpgrade: -1'),
 ('FrostBite',
  '霜噬',
  '给予2层寒霜，造成{Damage}点伤害。你在本场战斗中每施加过一次寒霜，这张牌就额外造成{Extra}点伤害。',
  '1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 5, Amount: 1, Extra: 2, ExtraUpgrade: 1'),
 ('IceBreak',
  '冰断',
  '对所有敌人造成{Damage}点伤害，给予{Amount}层寒霜。消耗敌人身上所有的寒霜，每消耗1层这张牌就额外造成{Extra}点伤害。',
  '2, CardType.Attack, CardRarity.Rare, TargetType.AllEnemies, Damage: 10, Amount: 10, AmountUpgrade: 2, Extra: 2, ExtraUpgrade: 1'),
 ('SnowUnsheathed',
  '雪、出鞘',
  '造成{Damage}点伤害。你在本回合每给予敌人1层负面状态，就给予敌人{Amount}层寒霜。',
  '1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy, Damage: 9, DamageUpgrade: 2, Amount: 1, AmountUpgrade: 1'),
 ('HypothermiaStrike', '失温打击', '造成{Damage}点伤害，给予等量于所造成伤害的寒霜。', '1, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy, Damage: 7, DamageUpgrade: 2'),
 ('WhiteNightRush',
  '白夜奔袭',
  '对所有敌人造成{Damage}点伤害，将这张牌置于你的冷藏牌堆。本场战斗中，这张牌每被置于冷藏牌堆一次，此牌的耗能就减少1点能量。',
  '5, CardType.Attack, CardRarity.Rare, TargetType.AllEnemies, Damage: 18, DamageUpgrade: 6'),
 ('Pierce',
  '贯穿',
  '对所有敌人造成{Damage}点伤害{Amount}次，分别将一张耗尽加入你的抽牌堆和弃牌堆。\n消耗。',
  '0, CardType.Attack, CardRarity.Rare, TargetType.AllEnemies, Damage: 7, Amount: 4, AmountUpgrade: 1, Exhaust: true'),
 ('Depleted', '耗尽', '此牌出现在手牌中后，你本回合不能再抽牌。', '-1, CardType.Status, CardRarity.Status, TargetType.None, Unplayable: true, Ethereal: true'),
 ('SnowCharge',
  '踏雪破阵',
  '造成{Damage}点伤害，将自己的雪势层数翻倍。\n消耗。',
  '3, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy, Damage: 17, DamageUpgrade: 4, Exhaust: true'),
 ('FatedStory', '命定的物语', '解冻牌下1次打出获得重放1。', '2, CardType.Power, CardRarity.Ancient, TargetType.Self, InnateUpgrade: true'),
 ('AbsoluteBeam', '极冻光束', '造成{Damage}点伤害，给予敌人寒霜上限一半的寒霜。', '1, CardType.Attack, CardRarity.Ancient, TargetType.AnyEnemy, Damage: 9, DamageUpgrade: 2'),
 ('GuardAdvance',
  '守护、前行',
  '获得{Amount}层冰甲X次，获得{Extra}层雪势X次。',
  '0, CardType.Skill, CardRarity.Uncommon, TargetType.Self, Amount: 6, AmountUpgrade: 2, Extra: 6, ExtraUpgrade: 2, CostsX: true'),
 ('IceRelease', '冰释', '下X张非X费解冻牌下次打出耗能变为0点能量。', '0, CardType.Skill, CardRarity.Rare, TargetType.Self, CostsX: true')]
