powers = {'GlacierBodyPower': ('冰川形态', '每回合获得{Amount}层冰甲。你的冰甲不再自然融化。'),
 'StormCorePower': ('风暴核心', '每回合获得{Amount}层雪势。'),
 'SnowEyePower': ('雪眼', '每当你打出冰晶，获得{Amount}层雪势。'),
 'IceMirrorPower': ('冰镜圣所', '每当你解冻1张牌，获得{Amount}层冰甲。'),
 'GlacialCorePower': ('极寒晶核', '冰晶额外施加{Amount}层寒霜。'),
 'CrystalEdgePower': ('晶锋', '冰晶额外造成{Amount}点伤害，且无视格挡。'),
 'CrystalAmuletPower': ('冰晶护符', '每当你消耗冰晶，获得{Amount}层冰甲。'),
 'IceCellarPower': ('冰窖', '每当你解冻1张牌，抽{Amount}张牌。'),
 'CrystalResonancePower': ('晶群共鸣', '每次生成冰晶时，额外生成{Amount}张。'),
 'WinterArchivePower': ('漫冬', '回合结束时，冷藏至多{Amount}张手牌。'),
 'EndlessStormPower': ('永夜风暴', '雪势在回合结束时只减少{Decay}层。'),
 'SixfoldSnowPower': ('积雪', '每回合第一次解冻牌时，获得{Amount}层冰甲。'),
 'HiddenBladePower': ('藏锋秘术', '攻击牌解冻后的下一次打出增加{Amount}点伤害。'),
 'ColdBloodEchoPower': ('寒血回响', '自霜使你失去生命时，获得损失生命{Amount}倍的冰甲。'),
 'HeatExchangePower': ('热交换', '每回合首次解冻牌时，获得{Amount}点能量。'),
 'DrawNextPower': ('冬日筹备', '下回合多抽{Amount}张牌。'),
 'FrostPower': ('寒霜', '累积至门槛时冰封，跳过一次行动。人工制品可抵消寒霜。'),
 'IceArmorPower': ('冰甲', '后于格挡结算，每层抵挡1点伤害（只能抵挡伤害，不能抵挡“失去生命”）并消耗。每回合抽牌前融化，剩余冰甲减半（向上取整）。'),
 'SelfFrostPower': ('自霜', '下回合抽牌前失去{Amount}点生命，然后移除此状态。'),
 'SnowPower': ('雪势', '回合结束对所有敌人造成{Amount}点非攻击伤害，然后层数减半（向下取整）。'),
 'ColdExpansionPower': ('冷库扩张', '冷藏容量+{Amount}（最多10）。'),
 'SlowReleasePower': ('速释装置', '回合开始时额外解冻{Amount}张牌。'),
 'ColdStoragePower': ('冷藏', '回合开始时解冻1张牌。解冻牌下次打出费用-1。'),
 'ArmorNextPower': ('下回合冰甲', '下回合获得{Amount}层冰甲。'),
 'ThawNextPower': ('下回合解冻', '下回合额外解冻{Amount}张牌。'),
 'BlessingWindPower': ('祝福之风', '敏捷现在可以在你获得冰甲时应用。'),
 'HeartInscriptionPower': ('铭刻于心', '力量现在可以在你获得雪势时应用。'),
 'FlowingPowerPower': ('流淌而出的强大力量', '你生成的冰晶会被升级。'),
 'SelfFrostGuardPower': ('暴雪庇护', '阻止你接下来{Amount}次获得自霜。'),
 'FatedStoryPower': ('命定的物语', '解冻牌下次打出获得重放{Amount}。'),
 'IceReleasePower': ('冰释', '下{Amount}张非X费解冻牌下次打出免费。'),
 'FractalSnowPower': ('分形雪花', '本场战斗中，生成的冰晶获得锐利。')}

powers['EclipseStrengthPower']=('日食·临时力量','本回合获得{Amount}点力量。回合结束时移除，不被人工制品抵消。')