"""The manifest is the sole source of the mod version."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def version():
    return json.loads((ROOT / 'mod_manifest.json').read_text('utf-8-sig'))['version']


def generate():
    value = version()
    target = ROOT / 'Source' / 'VersionInfo.Generated.cs'
    content = ('// Generated by tools/version_info.py from mod_manifest.json.\n'
               'namespace Frostsworn;\n'
               f'public static class FrostVersion {{ public const string Value = {json.dumps(value)}; }}\n')
    if not target.exists() or target.read_text('utf-8-sig') != content:
        target.write_text(content, encoding='utf-8')
    print(f'Version: {value}')


if __name__ == '__main__':
    generate()
